[package]
name = "imgurs"
version = "0.8.1"
description = "API and CLI for Imgur"
license = "BSD-3-Clause"
readme = "README.md"
authors = ["MedzikUser <nivua1fn@duck.com>"]
homepage = "https://github.com/MedzikUser/imgurs"
repository = "https://github.com/MedzikUser/imgurs.git"
keywords = ["imgur", "imgur-api", "image", "image-upload"]
categories = ["command-line-utilities"]
rust-version = "1.58"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1

[dependencies]
dirs = "4.0.0"
toml = "0.5.9"
chrono = "0.4.19"
base64 = "0.13.0"
notify-rust = "4.5.8"
clap_complete = "3.2.3"
anyhow = "1.0.58"
better-panic = "0.3.0"
validator = "0.16.0"
colored = "2.0.0"
clap_mangen = "0.1.10"
thiserror = "1.0.31"
serde_json = "1.0.82"
serde = { version = "1.0.140", features = ["derive"] }
clap = { version = "3.2.16", features = ["derive"] }
log = { version = "0.4.17", features = ["release_max_level_info", "max_level_debug"] }
simple_logger = { version = "2.2.0", default-features = false, features = ["colors"] }
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }

[target.'cfg(not(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")))))'.dependencies]
arboard = "2.1.1"
