[package]
name = "imgurs"
description = "API and CLI for Imgur"
license = "BSD-3-Clause"
readme = "README.md"
authors = ["MedzikUser <nivua1fn@duck.com>"]
homepage = "https://github.com/MedzikUser/imgurs"
repository = "https://github.com/MedzikUser/imgurs.git"
keywords = ["imgur", "imgur-api", "image", "image-upload"]
categories = ["command-line-utilities"]
rust-version = "1.58"
version = "0.7.2"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1

[dependencies]
dirs = "4.0.0"
serde = "1.0.136"
serde_derive = "1.0.136"
toml = "0.5.9"
serde_json = "1.0.79"
chrono = "0.4.19"
base64 = "0.13.0"
notify-rust = "4.5.8"
clap_complete = "3.1.2"
anyhow = "1.0.57"
better-panic = "0.3.0"
validator = "0.14.0"
colored = "2.0.0"
clap_mangen = "0.1.6"
discord-webhook = "0.1.0"

[target.'cfg(not(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")))))'.dependencies]
arboard = "2.1.0"

[dependencies.clap]
version = "3.1.11"
features = ["derive", "cargo", "std"]

[dependencies.log]
version = "0.4.16"
features = ["release_max_level_info", "max_level_debug"]

[dependencies.simple_logger]
version = "2.1.0"
default-features = false
features = ["colors"]

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["json", "rustls-tls"]

[dependencies.tokio]
version = "1.17.0"
features = ["macros", "rt-multi-thread"]
