[workspace]
members = ["imgurs-cli"]
resolver = "2"

[package]
name = "imgurs"
version = "0.8.1"
description = "API for Imgur"
license = "BSD-3-Clause"
authors = ["MedzikUser <nivua1fn@duck.com>"]
homepage = "https://github.com/MedzikUser/imgurs"
repository = "https://github.com/MedzikUser/imgurs.git"
keywords = ["imgur", "imgur-api", "image", "image-upload"]
rust-version = "1.58"
edition = "2021"

[features]
default = ["imgur"]
full = ["imgur", "null_pointer"]
imgur = []
null_pointer = []

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1

[dependencies]
base64 = "0.13.0"
notify-rust = "4.5.8"
validator = "0.16.0"
thiserror = "1.0.32"
serde_json = "1.0.85"
serde = { version = "1.0.144", features = ["derive"] }
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }

[dev-dependencies]
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
