# https://rust-lang.github.io/rustfmt

# stable
edition = "2021"
newline_style = "Unix"
match_block_trailing_comma = true

# nightly
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
format_code_in_doc_comments = true
