[package]
name = "imgurs-cli"
version = "0.8.1"
description = "CLI for Imgur"
license = "BSD-3-Clause"
authors = ["MedzikUser <nivua1fn@duck.com>"]
homepage = "https://github.com/MedzikUser/imgurs"
repository = "https://github.com/MedzikUser/imgurs.git"
keywords = ["imgur", "imgur-api", "image", "image-upload"]
categories = ["command-line-utilities"]
rust-version = "1.58"
edition = "2021"

[[bin]]
name = "imgurs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.64"
clap = { version = "3.2.20", features = ["derive"] }
clap_complete = "3.2.4"
clap_mangen = "0.1.11"
chrono = "0.4.22"
colored = "2.0.0"
notify-rust = "4.5.8"
better-panic = "0.3.0"
dirs = "4.0.0"
log = "0.4.17"
simple_logger = "2.3.0"
toml = "0.5.9"
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
imgurs = { path = "..", features = ["full"] }

[target.'cfg(not(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")))))'.dependencies]
arboard = "2.1.1"
